# Generated by Django 4.0.4 on 2022-05-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0009_remove_posts_hagtags_posts_hagtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='notification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='socialmediaapp.notification'),
        ),
        migrations.AlterField(
            model_name='like',
            name='notification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='like', to='socialmediaapp.notification'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='hagtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='socialmediaapp.hastag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='socialmediaapp.userrole'),
        ),
    ]
