# Generated by Django 4.0.4 on 2022-05-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0012_rename_articles_hastag_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hastag',
            name='posts',
        ),
        migrations.AddField(
            model_name='posts',
            name='hagtags',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='socialmediaapp.hastag'),
        ),
    ]
