# Generated by Django 4.0.4 on 2022-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0016_alter_posts_hagtags_alter_postview_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='users/%Y/%m'),
        ),
    ]
