# Generated by Django 4.0.4 on 2022-05-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0022_alter_posts_hagtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='active',
        ),
    ]
