# Generated by Django 4.0.4 on 2022-05-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='status',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/'),
        ),
    ]
