# Generated by Django 4.0.4 on 2022-05-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0003_auctionsdetails_posts_delete_action_delete_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
