# Generated by Django 4.0.4 on 2022-05-05 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0004_comment_created_date_like_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmediaapp.comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='like',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmediaapp.like'),
        ),
    ]
