# Generated by Django 4.0.4 on 2022-05-06 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0008_alter_posts_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='hagtags',
        ),
        migrations.AddField(
            model_name='posts',
            name='hagtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialmediaapp.hastag'),
        ),
    ]
