# Generated by Django 4.0.4 on 2022-05-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0010_alter_comment_notification_alter_like_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='hagtag',
        ),
        migrations.AddField(
            model_name='hastag',
            name='articles',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='socialmediaapp.posts'),
        ),
    ]
