# Generated by Django 4.0.4 on 2022-05-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0011_remove_posts_hagtag_hastag_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hastag',
            old_name='articles',
            new_name='posts',
        ),
    ]
