# Generated by Django 4.0.4 on 2022-05-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0014_alter_comment_unique_together_comment_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='socialmediaapp.posts'),
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('counter', models.IntegerField(default=0)),
                ('posts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialmediaapp.posts', unique=True)),
            ],
        ),
    ]
