# Generated by Django 4.0.4 on 2022-05-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0017_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='hagtags',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='socialmediaapp.hastag'),
        ),
    ]
